authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name = 'login'),
    path('logout/', authapp.logout, name = 'logout'),
    path('profile/', authapp.profile, name = 'profile'),
    path('register/', authapp.register, name = 'register'),

    path('verify/<email>/<activation_key>', authapp.verify, name = 'verify')
]

shop/urls.py
from django.urls import path, include, re_path
from django.contrib import admin
from mainapp import views as mainapp_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp_views.main, name = 'main'),
    path('products/', include('mainapp.urls', namespace = 'products')),
    path('auth/', include('authapp.urls')),
    path('baskets/', include('basketapp.urls', namespace = 'baskets')),
    path('admin-staff/', include('adminapp.urls', namespace = 'admin-staff')),
    path('order/', include('ordersapp.urls', namespace = 'order')),

    # path('text_context/', mainapp_views.text_context),

    path('', include('social_django.urls', namespace = 'social')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

authapp/models.py
from datetime import timedelta

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now


class User(AbstractUser):
    avatar = models.ImageField(upload_to = 'users_avatar', blank = True)
    age = models.PositiveIntegerField(blank = True, null = True)
    activation_key = models.CharField(max_length = 128, blank = True, null = True)
    activation_key_expires = models.DateTimeField(default = (now() + timedelta(hours = 48)))

    def __str__(self):
        return self.username

    def is_activation_key_expired(self):
        if now() < self.activation_key_expires:
            return False
        return True


class UserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'W'

    GENDER_CHOICES = (
        (MALE, 'М'),
        (FEMALE, 'Ж'),
    )

    user = models.OneToOneField(User, unique = True, null = False, db_index = True, on_delete = models.CASCADE)
    tagline = models.CharField(verbose_name = 'теги', max_length = 128, blank = True)
    aboutMe = models.TextField(verbose_name = 'о себе', max_length = 512, blank = True)
    gender = models.CharField(verbose_name = 'пол', max_length = 1, choices = GENDER_CHOICES, blank = True)

    @receiver(post_save, sender = User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user = instance)

    @receiver(post_save, sender = User)
    def save_user_profile(sender, instance, **kwargs):
        instance.userprofile.save()

authapp/forms.py
import hashlib
import random

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from authapp.models import User, UserProfile


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['password'].widget.attrs['placeholder'] = 'Введите пароль'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['email'].widget.attrs['placeholder'] = 'Введите email'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Введите имя'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Введите фамилию'
        self.fields['password1'].widget.attrs['placeholder'] = 'Введите пароль'
        self.fields['password2'].widget.attrs['placeholder'] = 'Повторите пароль'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'

    def save(self, **kwargs):
        user = super(UserRegisterForm, self).save()
        user.is_active = False
        salt = hashlib.sha1(str(random.random()).encode('utf8')).hexdigest()[:6]
        user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()
        user.save()

        return user


class UserProfileForm(UserChangeForm):
    avatar = forms.ImageField(widget = forms.FileInput())

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'avatar', 'age')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['email'].widget.attrs['readonly'] = True
        self.fields['avatar'].widget.attrs['class'] = 'custom-file-input'

class UserProfileEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('tagline', 'aboutMe', 'gender')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['gender'].widget.attrs['class'] = 'form-control py-2 dropdown-toggle'

authapp/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from authapp.forms import UserLoginForm, UserRegisterForm, UserProfileForm, UserProfileEditForm
from authapp.models import User
from basketapp.models import Basket


def send_verify_email(user):
    # TODO сделать отправку писем на реальную почту и приема ссылки с нее

    verify_link = reverse('authapp:verify', args = [user.email, user.activation_key])

    subject = f'подтверждение учетной записи {user.username}'
    message = f'Для подтверждения пройдите по ссылке {settings.DOMAIN}{verify_link}'

    return send_mail(subject, message, settings.EMAIL_HOST_USER, [user.email], fail_silently = False)


def verify(request, email, activation_key):
    try:
        user = User.objects.get(email = email)
        if user.activation_key == activation_key and not user.is_activation_key_expired():
            user.is_active = True
            activation_key = None
            user.save()
            auth.login(request, user)
            return render(request, 'authapp/verification.html')
    except Exception as ex:
        return HttpResponseRedirect(reverse('main'))

# @csrf_exempt
def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data = request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']

            user = auth.authenticate(username = username, password = password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main'))
    else:
        form = UserLoginForm()

    context = {'form': form}
    return render(request, 'authapp/login.html', context = context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(data = request.POST)
        if form.is_valid():
            user = form.save()
            if send_verify_email(user):
                messages.success(request,
                                 'Вы успешно зарегистрировались!Ссылка для активации акаунта выслана Вам на почту!')

            return HttpResponseRedirect(reverse('authapp:login'))

    else:
        form = UserRegisterForm()

    context = {'form': form}

    return render(request, 'authapp/register.html', context = context)


def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(data = request.POST, files = request._files, instance = request.user)
        profile_form = UserProfileEditForm(data = request.POST, instance = request.user.userprofile)

        if form.is_valid() and profile_form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('authapp:profile'))
    else:
        form = UserProfileForm(instance = request.user)
        profile_form = UserProfileEditForm(instance = request.user.userprofile)
    context = {
        'form': form,
        'profile_form': profile_form,
        'baskets': Basket.objects.filter(user = request.user).select_related()
    }
    return render(request, 'authapp/profile.html', context = context)

authapp/templates/authapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ titlepage|title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}


{% block content %}
    <div class="col-lg-5">
        {% if messages or form.non_field_errors %}
            <div class="alert
            {% if messages %} alert-success {% else %} alert-warning {% endif %}
             alert-dismissible fade show" role="alert" style="margin-top: 50px;">
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                {% else %}
                    {% for error in form.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="card shadow-lg border-0 rounded-lg mt-5">
            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
            </div>
            <div class="card-body">
                <form action="{% url 'authapp:login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                        {{ form.password }}
                    </div>
                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                        <a class="small" href="#">Забыли пароль?</a>
                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                    </div>


                </form>
            </div>
            <div class="card-footer text-center">
                <div class="small"><a href="{% url 'authapp:register' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
                <div class="small"><a href="{% url 'social:begin' 'vk-oauth2' %}?next=/">Войти через ВК</a></div>
            </div>
        </div>
    </div>
{% endblock %}

authapp/templates/authapp/profile.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ title|title }}
{% endblock %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <h4 class="mt-3 mb-3">Профиль</h4>
                <div class="col-lg-12 text-center">
                    <img width="100" height="100"
                         src="{% if user.avatar %} {{ user.avatar.url }} {% else %} {% static 'vendor/img/users/default_avatar.jpg' %} {% endif %}"
                         class="img-thumbnail">
                </div>
                <form action="{% url 'authapp:profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
{#                    <div class="form-row mb-2">#}
{#                        <div class="col-lg-12">#}
{#                            <div class="custom-file">#}
{#                                {{ form.avatar }}#}
{#                                <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">Выберите#}
{#                                    изображение</label>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                            {{ form.age }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ profile_form.gender.id_for_label }}">Пол</label>
                            {{ profile_form.gender }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ profile_form.tagline.id_for_label }}">Тэги</label>
                            {{ profile_form.tagline }}
                        </div>
                        <div class="col-lg-12">
                            <label class="small mb-1" for="{{ profile_form.aboutMe.id_for_label }}">Обо мне</label>
                            {{ profile_form.aboutMe }}
                        </div>

                    </div>

{#                    {{ form.as_p }}#}
{#                    {{ profile_form.as_p }}#}
                    <div class="form-row">
                        {#                        <div class="col-lg-6">#}
                        {#                            <label class="small mb-1" for="inputBirthday">День рождения</label>#}
                        {#                            <input class="form-control py-4" id="inputBirthday" type="date"#}
                        {#                                   aria-describedby="birthdayHelp" value="1998-01-13"/>#}
                        {#                        </div>#}
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-5">
                {% include 'basket.html' %}
            </div>
        </div>
    </div>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}


{% block content %}
    <div class="col-lg-7">
        <div class="alert alert-warning alert-dismissible fade show" role="alert"
             style="margin-top: 50px;">
            <strong>Holy guacamole!</strong> You should check in on some of those fields below.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="card shadow-lg border-0 rounded-lg mt-5">
            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
            </div>
            <div class="card-body">
                <form action="{% url 'authapp:register' %}" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}

                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-6">
                            <label class="small mb-1" for="{{ form.username.label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                                {{ form.password1 }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                    пароля</label>
                                {{ form.password2 }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group mt-4 mb-0">
                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <div class="small"><a href="{% url 'authapp:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
            </div>
        </div>
    </div>
{% endblock %}

authapp/templates/authapp/verification.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}
{% block content %}
    {% if user.is_authenticated %}
        <h3>Поздравляем!</h3>
        <br>
        <h4>Пользователь {{ user.username }} подтвержден.</h4>
    {% else %}
        <h3>Верификация не пройдена.</h3>
    {% endif %}
    <br>
    <button class="btn btn-round form-control">
        <a href="{% url 'main' %}" class="">на главную</a>
    </button>
{% endblock %}