ordersapp/urls.py
from django.urls import path
import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
	path('', ordersapp.OrderList.as_view(), name='orders'),
	path('order_create/', ordersapp.OrderCreate.as_view(), name='order_create'),
	path('update/<pk>/', ordersapp.OrderUpdate.as_view(), name='order_update'),
	path('delete/<pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
	path('detail/<pk>/', ordersapp.OrderDetail.as_view(), name='order_detail'),
	path('forming/<pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),

	path('product/<pk>/price/', ordersapp.get_product_price, name='get_product_price'),

]

shop/urls.py
from django.urls import path, include, re_path
from django.contrib import admin
from mainapp import views as mainapp_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp_views.main, name = 'main'),
    path('products/', include('mainapp.urls', namespace = 'products')),
    path('auth/', include('authapp.urls')),
    path('baskets/', include('basketapp.urls', namespace = 'baskets')),
    path('admin-staff/', include('adminapp.urls', namespace = 'admin-staff')),
    path('order/', include('ordersapp.urls', namespace = 'order')),

    # path('text_context/', mainapp_views.text_context),

    path('', include('social_django.urls', namespace = 'social')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

ordersapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete = models.CASCADE
    )

    created_at = models.DateTimeField(
        verbose_name = 'создан',
        auto_now_add = True
    )

    updated_at = models.DateTimeField(
        verbose_name = 'обновлен',
        auto_now = True
    )

    status = models.CharField(
        verbose_name = 'статус',
        max_length = 3,
        choices = ORDER_STATUS_CHOICES,
        default = FORMING
    )
    is_active = models.BooleanField(verbose_name = 'активен', default = True)

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'
        ordering = ('-created_at',)

    def get_total_quantity(self):
        _items = self.orderitems.select_related()
        return sum(item.quantity for item in _items)

    def get_total_cost(self):
        _items = self.orderitems.select_related()
        return sum(item.quantity * item.product.price for item in _items)

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()
        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        related_name = "orderitems",
        on_delete = models.CASCADE
    )

    product = models.ForeignKey(
        Product,
        verbose_name = 'продукт',
        on_delete = models.CASCADE
    )

    quantity = models.PositiveIntegerField(
        verbose_name = 'количество',
        default = 0
    )

    def get_product_cost(self):
        return self.product.price * self.quantity


    @staticmethod
    def get_item(pk):
        return OrderItem.objects.filter(pk=pk).first()

ordersapp/forms.py
from django import forms

from mainapp.models import Product
from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label = 'цена', required = False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['product'].queryset = Product.get_items().select_related()

ordersapp/views.py
from django.db import transaction
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from basketapp.models import Basket
from mainapp.models import Product
from ordersapp.forms import OrderItemForm
from ordersapp.models import Order, OrderItem


class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user = self.request.user)


class OrderCreate(CreateView):
    model = Order

    fields = []
    success_url = reverse_lazy('order:orders')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        OrderFormSet = inlineformset_factory(
            Order,
            OrderItem,
            form = OrderItemForm,
            extra = 1
        )
        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user = self.request.user)
            if basket_items.exists():
                OrderFormSet = inlineformset_factory(
                    Order,
                    OrderItem,
                    form = OrderItemForm,
                    extra = basket_items.count()
                )
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
            else:
                formset = OrderFormSet()
        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']
        basket_items = Basket.objects.filter(user = self.request.user)
        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()
            if basket_items.exists():
                basket_items.delete()

        if self.object.get_total_cost() == 0:
            self.object.delete()
        return super().form_valid(form)


class OrderUpdate(UpdateView):
    model = Order

    fields = []
    success_url = reverse_lazy('order:orders')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        OrderFormSet = inlineformset_factory(
            Order,
            OrderItem,
            form = OrderItemForm,
            extra = 1
        )
        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance = self.object)
        else:
            queryset = self.object.orderitems.select_related()
            formset = OrderFormSet(instance = self.object, queryset = queryset)
            # formset = OrderFormSet(instance = self.object)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price
        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()
        return super().form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('order:orders')


class OrderDetail(DetailView):
    model = Order


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk = pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()
    return HttpResponseRedirect(reverse('ordersapp:orders'))


def get_product_price(request, pk):
    if request.is_ajax():
        product_item = Product.objects.filter(pk = int(pk)).first()
        if product_item:
            return JsonResponse({'price': product_item.price})
        return JsonResponse({'price': 0})

ordersapp/templates/ordersapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ titlepage|title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                        {% block content %}

                        {% endblock %}
                </div>
            </main>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/auth-admin.js' %}"></script>
    <script src="{% static 'js/order_script.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
</body>
</html>

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="category_delete">
        <div class="h1">Уверены, что хотите удалить?</div>
        {% include 'ordersapp/includes/inc_order_summary.html' %}
        <form action="{% url 'ordersapp:order_delete' object.pk %}"
              method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'ordersapp:orders' %}">отмена</a>
        </button>
    </div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "ordersapp/base.html" %}
{% load staticfiles %}
{% load my_tags %}
{% block content %}
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="basket_list">
        {% for item in object.orderitems.select_related %}
            <div class="basket_record">
{#                <img class="card-img-top" src="{{ item.product.image|media_folder_products }}"#}
{#                     alt="{{ item.product.short_description }}">#}
{#                TODO Сделать стили картинки, чтобы влезала#}
                <span class="category_name">{{ item.productcategory.name }}</span>
                <span class="product_name">{{ item.product.name }}</span>
                <span class="product_price">{{ item.product.price }}&nbspруб</span>
                <span class="product_quantitiy">x {{ item.quantity }} шт.</span>
                <span class="product_cost">= {{ item.get_product_cost }}&nbspруб</span>
            </div>
        {% endfor %}
    </div>
    {% include 'ordersapp/includes/inc_order_actions.html' %}
{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load staticfiles %}

{% block content %}
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                    {{ field.label|capfirst }}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                {% if forloop.first %}

                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {% if field.name == 'price' %}
                                    {% if field.value %}
                                        <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                            {{ field.value }}
                                        </span> руб.

                                    {% endif %}
                                {% else %}
                                    {{ field }}
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">
                сохранить
            </button >
            {% include 'ordersapp/includes/inc_order_actions.html' %}
        </form>
    </div>
{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="h2 text-center head">
        Ваши заказы,
        {% if user.first_name %}
            {{ user.first_name|title }}
        {% else %}
            Пользователь
        {% endif %}
    </div>
    <table class="table orders_list">
        <thead>
        <tr>
            <th>ID</th>
            <th>Создан</th>
            <th>Обновлен</th>
            <th>Статус</th>
        </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            {% if item.is_active %}
                <tr>
                    <td class="td1 orders_list">{{ item.pk }}</td>
                    <td>{{ item.created_at|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.updated_at|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.get_status_display }}</td>
                    <td>
                        <a href="{% url 'ordersapp:order_detail' item.pk %}">
                            посмотреть
                        </a>
                    </td>
                    <td>
                        {% if item.status == 'FM' %}
                            <a href="{% url 'ordersapp:order_update' item.pk %}">
                                редактировать
                            </a>
                        {% endif %}
                    </td>
                    <td>
                        {% if item.status == 'FM' %}
                            <a href="{% url 'ordersapp:order_delete' item.pk %}">
                                удалить
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
    <button class="btn btn-default btn-round">
        <a href="{% url 'main' %}">
            на главную
        </a>
    </button>
    <button class="btn btn-default btn-round">
        <a href="{% url 'ordersapp:order_create' %}">
            новый
        </a>
    </button>
{% endblock %}